import type { ReadingSessionData } from '../types';

// The virtual module is generated at build/dev time by vite-plugin-genki-txt in vite.config.ts
// @ts-expect-error virtual module generated by vite
import { readingTxtLessons as lessons } from 'virtual:genki-txt-lessons';

export const readingTxtLessons: ReadingSessionData[] = lessons;

export function getReadingTxtLessonById(id: string): ReadingSessionData | undefined {
  return readingTxtLessons.find(l => l.id === id);
}

