import path from 'path';
import { fileURLToPath } from 'url';
import { generateSeoArtifacts } from '../src/seo/generateSeoArtifacts';
// @ts-expect-error virtual module generated by vite
import { genkiTxtLessons, sentenceTxtLessons } from 'virtual:genki-txt-lessons';

const distDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../dist');

generateSeoArtifacts(distDir, {
  genkiLessons: genkiTxtLessons,
  sentenceLessons: sentenceTxtLessons,
});
