import type { TranslateSessionData } from '../types';

// The virtual module is generated at build/dev time by vite-plugin-genki-txt in vite.config.ts
// @ts-expect-error virtual module generated by vite
import { sentenceTxtLessons as lessons } from 'virtual:genki-txt-lessons';

export const sentenceTxtLessons: TranslateSessionData[] = lessons;

export function getSentenceTxtLessonById(id: string): TranslateSessionData | undefined {
  return sentenceTxtLessons.find(l => l.id === id);
}

